name: Build and deploy Capella Services to Kubernetes
on:
  workflow_dispatch:
jobs:
  generate:
    name: Generate Tag Number
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag number
        id: get-latest-version
        shell: pwsh
        run: |
          #tag number should match (e.g: v0.0.0 or v1.1.1)
          $version_regex = "^v[0-9]+\.[0-9]+\.[0-9]+$"
          $tags = (git tag | sort -V) -match $version_regex
          echo "Existing tags:"
          foreach ($tag in $tags) {
            echo $tag
          }
          # echo $tags
          if ($tags.Count -gt 0) {
            echo "prev_tag=$tags[-1]"
            $latest_tag = $tags[-1]
          } else {
            echo "There is no tag yet. Hence tagging for sure."
            $latest_tag = "1.0.0"
          }
          
          echo "latest_tag=$latest_tag"
          echo "::set-output name=latest_tag::$latest_tag" 
        
