# Build and deploy teams
name: Build and deploy Teams Services to Kubernetes
on:
  workflow_dispatch:
env:
  SERVICES_PATH: "./src/services"
jobs:
  build_Image_and_deploy:
    name: "Build Image and Deploy"
    runs-on: ubuntu-latest
    steps:          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: premanshu
            password: Pragyan@2010
