name: Build and deploy Teams Services to docker
on:
  workflow_dispatch
env:
  SERVICES_PATH: "./src/services"
jobs:
  build_Image_and_deploy:
    name: "Build Image and Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: premanshu
            password: ${{ secrets.DOCKER_PAT }}            
      - name: Deploys application
        run: |
          docker build -t premanshu/teams:latest -f CallCenter/backend/src/teams/dockerfile .
          docker push premanshu/teams:latest
